/*
 * Código derivado de Neuro-OS Genesis.
 * Propiedad Intelectual de Neuro-OS Genesis.
 *
 * Licensed under GNU GPL v3.
 */
#pragma once
#include <cstdint>
#include <string>
#include <vector>

namespace NWC {

/**
 * @brief Neural-to-Binary Bridge (Traductor de Voluntad de Bajo Nivel)
 *
 * This component bridges high-level "Will" (Neural Intents) to low-level
 * binary execution, maintaining compatibility with the NUASM ecosystem.
 */
class NeuralBinaryBridge {
public:
  NeuralBinaryBridge();
  ~NeuralBinaryBridge();

  /**
   * @brief Loads a binary file generated by NUASM.
   * @param filepath Path to the .bin file.
   * @return true if loaded successfully.
   */
  bool LoadNUASMBinary(const std::string &filepath);

  /**
   * @brief Translates a high-level "Will" command string into its
   * corresponding NUASM instruction set.
   * @param willCommand The high-level intent.
   * @param langCode The language of the command (e.g., "es", "en", "hi").
   * Default "es".
   */
  void TranslateWill(const std::string &willCommand,
                     const std::string &langCode = "es");

  /**
   * @brief Executes the current buffer of bytecode.
   */
  void Execute();

  /**
   * @brief Gets the current bytecode buffer.
   */
  const std::vector<uint8_t> &GetBytecode() const { return m_Bytecode; }

private:
  std::vector<uint8_t> m_Bytecode;

  // Internal state for the Neuro-Virtual-Machine context
  struct VMContext {
    uint64_t registers[16];
    bool carry;
    bool zero;
  } m_Context;

  void InternalLog(const std::string &msg);
};

} // namespace NWC
